spring:
  application:
    name: mine-manager
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  messages:
    encoding: UTF-8

application:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:86400000}

